
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Diagnostics;
using System.Linq;

public class DatabaseObjectsPlugin : IPlugin
{
    private List<ITemplate> _templates = new List<ITemplate>();
    const string PluginName = "SQL FK View Builder  Plugin";
    const string PluginDescription = "SQL FK View Builder Generator Plugin";
    public DatabaseObjectsPlugin()
    {
        _templates.Add(new FKViewsBuilder());
    }
    public string Description
    {
        get { return PluginName; }
    }

    public string Name
    {
        get { return PluginDescription; }
    }

    public System.Collections.Generic.List<ITemplate> Templates
    {
        get { return _templates; }
        set { _templates = value; }
    }

    public class FKViewsBuilder : ITemplate
    {

        const string TemplateName = "SQL FK View Builder Template";
        const string TemplateDescription = "SQL FK View Builder Template";
        const string TemplateOutputLanguage = "SQL";
        private ArrayList _arraylist = new ArrayList();
        private string _workingdir;
        private string _languageMappingFileName;
        private string _dbTargetMappingFileName;
        private const string GENERATED_FILE_NAME = ".sql";
        private const string GENERATED_FOLDER_NAME = ".SQL_Views\\";

        private ArrayList _refkeyList = new ArrayList();
        public bool Execute(MyMeta.IDatabase db, string workingDir, GenerationProject generationProject)
        {
            try
            {
                MyMeta.IDatabase _dataBase = db;

                System.Text.StringBuilder Output = new System.Text.StringBuilder();
                System.Text.StringBuilder extendedpropertiesbuilder = new System.Text.StringBuilder();
                string refColumns = "";
                string refFkColumns = "";
                string refFkJoins = "";
                string viewName = string.Empty;



                _workingdir = workingDir;


                Output.AppendLine("--Script Generated By OpenORM.NET at: " + DateTime.Now.ToLongDateString() + " " + DateTime.Now.ToShortTimeString());
                Output.AppendLine("--Plugin Version: " + System.Reflection.Assembly.GetExecutingAssembly().GetName().Version.ToString());
                Output.AppendLine("");
                Output.Append("USE [");
                Output.Append(_dataBase.Name);
                Output.AppendLine("]");
                Output.AppendLine("GO");
                // Loop through the tables the user select and generate the stored procs and save them to disk

                Output.AppendLine("SET XACT_ABORT ON");
                Output.AppendLine("");
                Output.AppendLine("BEGIN TRANSACTION");
                Output.AppendLine("");

                foreach (MyMeta.ITable refTable in _dataBase.Tables)
                {
                    _refkeyList = new ArrayList();
                    if (refTable.Selected)
                    {
                        extendedpropertiesbuilder.Clear();
                        string refTableName = refTable.Name;

                        if (refTable.PrimaryKeys.Count == 0)
                        {
                            Output.AppendLine("-- ERROR: Table '" + refTable.Name + "' must have a primary key");
                        }
                        else
                        {
                            viewName = GetTableFullNameAsAlias(refTable);

                            string destinationSchema = @"@@DESTINATION_SCHEMA@@";

                            Output.Append(BuildCreateAlterViewStatement(viewName, destinationSchema));

                            string refFrom = "FROM " + GetTableFullName(refTable)  + " AS "  + GetTableFullNameAsAlias(refTable) + Environment.NewLine;

                            Output.AppendLine("");
                            Output.AppendLine("AS");
                            Output.AppendLine("SELECT ");

                            refFkColumns = string.Empty;

                            List<MyMeta.ITable> refTablesCollection = new List<MyMeta.ITable>();


                            foreach (MyMeta.IColumn refColumn in refTable.Columns)
                            {
                                refColumns += " " + GetTableFullNameAsAlias(refTable) + "." + refColumn.Name + " As " + GetTableFullNameAsAlias(refTable) + "_" + refColumn.Name + "," + Environment.NewLine;

                                if(refColumn.Description.Length > 0)
                                {
                                    extendedpropertiesbuilder.AppendLine("EXEC sys.sp_addextendedproperty @name=N'Description', @value=N'" + refColumn.Description + "' , @level0type=N'SCHEMA',@level0name=N'" + destinationSchema + "', @level1type=N'VIEW',@level1name=N'"+ viewName+"', @level2type=N'COLUMN',@level2name=N'" + GetTableFullNameAsAlias(refTable) + "_" + refColumn.Name + "'");
                                    extendedpropertiesbuilder.AppendLine("GO");
                                    extendedpropertiesbuilder.AppendLine("");
                                }

                                foreach (MyMeta.IForeignKey refFk in refColumn.ForeignKeys)
                                {
                                    MyMeta.ITable refFkTable = ((MyMeta.IForeignKey)refFk).PrimaryTable;
                 
                                    MyMeta.Column fkColumn = (MyMeta.Column)refFk.ForeignColumns.FirstOrDefault();

                                    MyMeta.Column refFkJoinColumn = (MyMeta.Column)refFkTable.PrimaryKeys[0];
                                    string refFkTableName = refFkTable.Name;

                                    if (!refFkTable.Name.ToUpper().Equals(refTable.Name.ToUpper()))
                                    {
                                        refTablesCollection.Add(refFkTable);
                                        _refkeyList.Add(refFkTable.Name);
                                        int itemQuantity = 0;
                                        foreach (var item in refTablesCollection)
                                        {
                                            if (item.Equals(refFkTable))
                                                itemQuantity += 1;
                                        }
                                        string refFkEntity = string.Empty;
                                        if(itemQuantity > 1)
                                            refFkEntity = "_" + refColumn.Name;

                                        refFkJoins += " LEFT JOIN " + GetTableFullName(refFkTable) + " As " + GetTableFullNameAsAlias(refFkTable) + refFkEntity + " ON " + GetTableFullNameAsAlias(refFkTable) + refFkEntity + "." + refFkJoinColumn.Name + " = " + GetTableFullNameAsAlias(refTable) + "." + fkColumn.Name + Environment.NewLine;

                                        foreach (MyMeta.IColumn refFkColumn in refFkTable.Columns)
                                        {
                                            refFkColumns += " " + GetTableFullNameAsAlias(refFkTable) + refFkEntity + "." + refFkColumn.Name + " As " + GetTableFullNameAsAlias(refFkTable) + refFkEntity + "_" + refFkColumn.Name + "," + Environment.NewLine;

                                            if (refFkColumn.Description.Length > 0)
                                            {
                                                extendedpropertiesbuilder.AppendLine("EXEC sys.sp_addextendedproperty @name=N'Description', @value=N'" + refFkColumn.Description + "' , @level0type=N'SCHEMA',@level0name=N'" + destinationSchema + "', @level1type=N'VIEW',@level1name=N'" + viewName + "', @level2type=N'COLUMN',@level2name=N'" + GetTableFullNameAsAlias(refFkColumn.Table) + "_" + refFkColumn.Name + "'");
                                                extendedpropertiesbuilder.AppendLine("GO");
                                                extendedpropertiesbuilder.AppendLine("");
                                            }
                                        }
                                    }
                                }
                            }
                            string refAllColumns = refColumns.ToString() + refFkColumns.ToString();
                            refAllColumns = refAllColumns.ToString().Substring(0, refAllColumns.ToString().Length - 3) + Environment.NewLine;
                            Output.AppendLine(refAllColumns + refFrom + refFkJoins.ToString());
                            Output.AppendLine("GO ");

                            Output.AppendLine(extendedpropertiesbuilder.ToString());

                            refColumns = string.Empty;
                            refFkColumns = string.Empty;
                            refFkJoins = string.Empty;
                            refAllColumns = string.Empty;
                        }

                    }

                }


                Output.AppendLine("");
                Output.AppendLine("GO");
                Output.AppendLine("\tIF @@ERROR <> 0 ROLLBACK TRANSACTION;");
                Output.AppendLine("\tELSE ");
                Output.AppendLine("\tBEGIN");
                Output.AppendLine("\t\tCOMMIT TRANSACTION;");
                Output.AppendLine("\tEND");
                Output.AppendLine("");

                if (!_workingdir.EndsWith("\\"))
                    _workingdir += "\\";
                System.IO.Directory.CreateDirectory(_workingdir + _dataBase.Name.ToUpper() + GENERATED_FOLDER_NAME);
                string path = _workingdir + db.Name.ToUpper() + GENERATED_FOLDER_NAME + db.Name.ToUpper() + GENERATED_FILE_NAME;
                System.IO.StreamWriter sw = new System.IO.StreamWriter(path);


                sw.Write(Output.ToString());
                sw.Close();

                if (OnFileGenerated != null)
                {
                    OnFileGenerated(_workingdir + db.Name.ToUpper() + GENERATED_FOLDER_NAME + db.Name.ToUpper() + GENERATED_FILE_NAME);
                }
                return true;

            }
            catch (Exception ex)
            {
                if (OnException != null)
                {
                    OnException(ex);
                }
                return false;
            }
        }

        private string GetTableFullName(MyMeta.ITable table)
        {
            string returnResult = string.Empty;
            returnResult = table.Schema + "." + table.Name;

            return returnResult;
        }

        private string GetTableFullNameAsAlias(MyMeta.ITable table)
        {
            string returnResult = string.Empty;
            returnResult = table.Schema + table.Name;

            return returnResult;
        }
        private string GetEntityName(string entityName)
        {
            Int32 count = default(Int32);
            string result = entityName;
            foreach (string entity in _refkeyList)
            {
                if (entity.Equals(entityName))
                {
                    count += 1;
                }
            }
            if (count > 0)
            {
                result += "_" + count.ToString();

            }
            return result;

        }
        public string BuildCreateAlterStatement(string strProcName, string strSchema)
        {

            string strStatement = null;
            strStatement = "";


            // Drop and recreate
            //strStatement = strStatement & "IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID = OBJECT_ID('" & strProcName & "') AND sysstat & 0xf = 4)" & vbCrLf
            strStatement = strStatement + "IF  EXISTS (SELECT * FROM sys.objects WHERE name = '" + strProcName + "' AND type in (N'V'))" + Environment.NewLine;

            strStatement = strStatement + "    DROP PROCEDURE [" + strSchema.Trim() + "].[" + strProcName + "];" + Environment.NewLine;
            strStatement = strStatement + "GO" + Environment.NewLine;

            strStatement = strStatement + "CREATE PROCEDURE [" + strSchema.Trim() + "].[" + strProcName + "]";


            return strStatement;

        }
        public string BuildCreateAlterViewStatement(string strViewName, string strSchema)
        {

            string strStatement = null;
            strStatement = "";


            strStatement = strStatement + "IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[" + strSchema.Trim() + "].[" + strViewName + "]') AND type in (N'V'))" + Environment.NewLine;
            strStatement = strStatement + "    BEGIN " + Environment.NewLine;
            strStatement = strStatement + "         DROP VIEW [" + strSchema.Trim() + "].[" + strViewName + "];" + Environment.NewLine;
            strStatement = strStatement + "    END " + Environment.NewLine;
            strStatement = strStatement + "GO" + Environment.NewLine;

            strStatement = strStatement + "CREATE VIEW [" + strSchema.Trim() + "].[" + strViewName + "]";


            return strStatement;

        }

        public string Name
        {
            get { return TemplateName; }
        }


        public event OnExceptionEventHandler OnException;

        public string WorkingDir
        {
            get { return _workingdir; }
            set { _workingdir = value; }
        }

        public string Description
        {
            get { return TemplateDescription; }
        }

        public event OnInfoEventHandler OnInfo;


        public string OutputLanguage
        {
            get { return TemplateOutputLanguage; }
        }

        public event OnFileGeneratedEventHandler OnFileGenerated;

        public event OnPercentDoneEventHandler OnPercentDone;

        public string DbTargetMappingFileName
        {
            get { return _dbTargetMappingFileName; }
            set { _dbTargetMappingFileName = value; }
        }

        public string LanguageMappingFileName
        {
            get { return _languageMappingFileName; }
            set { _languageMappingFileName = value; }
        }

        public string GUID
        {
            get { return "27138c73-c79a-462a-8f51-3476991d42fd"; }
        }

        #region ITemplate Members

        #endregion
    }
    // End class FKViewsBuilder

}